export const CARGO = [
    { id: 1, cargo: "Todas las gerencias" },
    { id: 2, cargo: "Jefe de la Oficina de Gestión Empresarial" },
    { id: 3, cargo: "Coordinador del SIG" },
    { id: 4, cargo: "Responsable de Riesgos" },
    { id: 5, cargo: "Encargado de Prevención" },
    { id: 6, cargo: "Especialista en evaluación de Gestión" },
    { id: 7, cargo: "Jefe Departamento de Ingeniería" },
    { id: 8, cargo: "Supervisor de Finanzas" },
    { id: 9, cargo: "Jefe del Departamento de Comercialización" },
    { id: 10, cargo: "Comité de Procesos Regulatorios" },
    { id: 11, cargo: "Responsable de Comunicaciones y Responsabilidad Social" },
    { id: 12, cargo: "Jefe del Departamento de Operaciones" },
    { id: 13, cargo: "Jefe del Departamento de Distribución" },
    { id: 14, cargo: "Jefe del Departamento de Calidad / Jefe del Departamento de Control de Pérdidas" },
    { id: 15, cargo: "Jefe de la Oficina de Asesoría Legal" },
    { id: 16, cargo: "Jefe del Departamento de Contabilidad" },
    { id: 17, cargo: "Jefe del Departamento de Finanzas" },
    { id: 18, cargo: "Asistente de Control Patrimonial" },
    { id: 19, cargo: "Supervisor de Sistemas" },
    { id: 20, cargo: "Jefe del Departamento de Logistica" },
    { id: 21, cargo: "Auxiliar de Almacén" },
    { id: 22, cargo: "Jefe del Departamento de Recursos Humanos" },
    { id: 23, cargo: "Asistente Social" },
    { id: 24, cargo: "Asistente de Recursos Humanos" },
    { id: 25, cargo: "Gerente de Administración y Finanzas" }
]
