export const CATALOGO = {
    CATALOGO_FRECUENCIA_CONTROL: "FRECUENCIA_CONTROL",
    CATALOGO_OPORTUNIDAD_CONTROL: "OPORTUNIDAD_CONTROL",
    CATALOGO_AUTOMATIZACION_CONTROL: "AUTOMATIZACION_CONTROL",
    CATALOGO_GRUPO_INTERES: "GRUPO_INTERES",
    CATALOGO_NIVEL_MATRIZ: "NIVEL_MATRIZ",
    CATALOGO_ORIGEN_RIESGO: "ORIGEN_RIESGO",
    CATALOGO_FRECUENCIA_RIESGO: "FRECUENCIA_RIESGO",
    CATALOGO_TIPO_RIESGO: "TIPO_RIESGO",
    CATALOGO_ESTRATEGIA_RESPUESTA: "ESTRATEGIA_RESPUESTA",
    CATALOGO_ESTADO_PLAN: "ESTADO_PLAN",
}