export const USUARIOS = [
  { id: 1, nombres: "Daniela", apellidos: "Lopez Galán", estado: "Activo" },
  { id: 2, nombres: "Marco", apellidos: "Botton Tuttofare", estado: "Activo" },
  {
    id: 3,
    nombres: "Mariah",
    apellidos: "Maclachlan Better Half",
    estado: "Activo",
  },
  { id: 4, nombres: "Juan", apellidos: "Perez Gomez", estado: "Inactivo" },
  { id: 5, nombres: "Ana", apellidos: "Martinez Ruiz", estado: "Activo" },
  { id: 6, nombres: "Luis", apellidos: "Fernandez Lopez", estado: "Inactivo" },
  { id: 7, nombres: "Sofia", apellidos: "Garcia Torres", estado: "Activo" },
  {
    id: 8,
    nombres: "Carlos",
    apellidos: "Rodriguez Sanchez",
    estado: "Activo",
  },
  { id: 9, nombres: "Lucia", apellidos: "Hernandez Diaz", estado: "Inactivo" },
  { id: 10, nombres: "Miguel", apellidos: "Lopez Martinez", estado: "Activo" },
  { id: 11, nombres: "Elena", apellidos: "Gomez Fernandez", estado: "Activo" },
  { id: 12, nombres: "Pedro", apellidos: "Martinez Perez", estado: "Inactivo" },
  { id: 13, nombres: "Laura", apellidos: "Sanchez Garcia", estado: "Activo" },
  { id: 14, nombres: "Jorge", apellidos: "Diaz Rodriguez", estado: "Activo" },
  {
    id: 15,
    nombres: "Marta",
    apellidos: "Lopez Hernandez",
    estado: "Inactivo",
  },
  { id: 16, nombres: "Alberto", apellidos: "Gonzalez Ruiz", estado: "Activo" },
  {
    id: 17,
    nombres: "Cristina",
    apellidos: "Ramirez Torres",
    estado: "Activo",
  },
  {
    id: 18,
    nombres: "Fernando",
    apellidos: "Sanchez Diaz",
    estado: "Inactivo",
  },
  {
    id: 19,
    nombres: "Patricia",
    apellidos: "Garcia Martinez",
    estado: "Activo",
  },
  { id: 20, nombres: "Raul", apellidos: "Fernandez Lopez", estado: "Activo" },
  {
    id: 21,
    nombres: "Isabel",
    apellidos: "Rodriguez Sanchez",
    estado: "Inactivo",
  },
  { id: 22, nombres: "Sergio", apellidos: "Hernandez Diaz", estado: "Activo" },
  { id: 23, nombres: "Monica", apellidos: "Lopez Martinez", estado: "Activo" },
  {
    id: 24,
    nombres: "Antonio",
    apellidos: "Gomez Fernandez",
    estado: "Inactivo",
  },
  { id: 25, nombres: "Beatriz", apellidos: "Martinez Perez", estado: "Activo" },
  { id: 26, nombres: "Rafael", apellidos: "Sanchez Garcia", estado: "Activo" },
  {
    id: 27,
    nombres: "Silvia",
    apellidos: "Diaz Rodriguez",
    estado: "Inactivo",
  },
  { id: 28, nombres: "Victor", apellidos: "Lopez Hernandez", estado: "Activo" },
  { id: 29, nombres: "Natalia", apellidos: "Gonzalez Ruiz", estado: "Activo" },
  {
    id: 30,
    nombres: "Andres",
    apellidos: "Ramirez Torres",
    estado: "Inactivo",
  },
  { id: 31, nombres: "Rosa", apellidos: "Sanchez Diaz", estado: "Activo" },
  { id: 32, nombres: "Hugo", apellidos: "Garcia Martinez", estado: "Activo" },
  {
    id: 33,
    nombres: "Paula",
    apellidos: "Fernandez Lopez",
    estado: "Inactivo",
  },
  {
    id: 34,
    nombres: "Manuel",
    apellidos: "Rodriguez Sanchez",
    estado: "Activo",
  },
  { id: 35, nombres: "Alicia", apellidos: "Hernandez Diaz", estado: "Activo" },
  {
    id: 36,
    nombres: "Gonzalo",
    apellidos: "Lopez Martinez",
    estado: "Inactivo",
  },
  { id: 37, nombres: "Clara", apellidos: "Gomez Fernandez", estado: "Activo" },
  { id: 38, nombres: "Julian", apellidos: "Martinez Perez", estado: "Activo" },
  { id: 39, nombres: "Eva", apellidos: "Sanchez Garcia", estado: "Inactivo" },
  {
    id: 40,
    nombres: "Francisco",
    apellidos: "Diaz Rodriguez",
    estado: "Activo",
  },
];
