export {default as Login} from "./Login";
export {default as Home} from "./Home";
export { default as MantenedorUsuario } from "./MantenedorUsuario";
export { default as MantenedorCargo } from "./MantenedorCargo";
export { default as MantenedorArea } from "./MantenedorArea";
export { default as MantenedorGerencia } from "./MantenedorGerencia";
export { default as MantenedorMacroproceso } from "./MantenedorMacroproceso";
export { default as MantenedorProceso } from "./MantenedorProceso";
export { default as MantenedorSubProceso } from "./MantenedorSubProceso";
export { default as MantenedorPerfiles } from "./MantenedorPerfiles";
export { default as MantenedorMenu } from "./MantenedorMenu";
export { default as MantenedorAsigPerfiles } from "./MantenedorAsigPerfiles";
export { default as MantenedorPermisosMenu } from "./MantenedorPermisosMenu";
export { default as MatrizCambioSignificativo } from "./MatrizCS";
export { default as MantenedorGestionRiesgo } from "./MantenedorGestionRiesgo";
export { default as MantenedorGrupoInteres } from "./MantenedorGrupoInteres";
export { default as MantenedorFoda } from "./MantenedorFoda";
export { default as PruebaComponent } from "./Prueba";
